diff --git a/src/bcftools-1.22/Makefile b/src/bcftools-1.22/Makefile.orig
index 4e24c9c..1abb039 100644
--- a/src/bcftools-1.22/Makefile
+++ b/src/bcftools-1.22/Makefile.orig
@@ -26,7 +26,7 @@ CC       = gcc
 AR       = ar
 RANLIB   = ranlib
 CPPFLAGS =
-CFLAGS   = -g -Wall -O2 -fPIC -Wno-alloc-size-larger-than
+CFLAGS   = -g -Wall -O2 -fPIC
 LDFLAGS  =
 LIBS     =
 
@@ -107,7 +107,7 @@ endif
 
 include config.mk
 
-PACKAGE_VERSION = 1.22
+PACKAGE_VERSION = 1.21
 
 # If building from a Git repository, replace $(PACKAGE_VERSION) with the Git
 # description of the working tree: either a release tag with the same value
